name: Push to Deploy Repo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  push-to-deploy-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Clone Deploy Repo
        run: |
          git clone https://github.com/staccato20/FitnessMate-FE-Deploy.git deploy

      - name: Remove all files in Deploy Repo
        run: |
          rm -rf deploy/*

      - name: Copy files to Deploy Repo
        run: |
          rsync -av --delete --exclude='.git' --exclude='node_modules/' --exclude='deploy/' . deploy/
          ls -al deploy/ # 복사된 파일 확인

      - name: Commit and Push changes to Deploy Repo
        run: |
          cd deploy
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "Update from Frontend repo by ${{ github.actor }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.FITMATE_STACCATO20 }}@github.com/staccato20/FitnessMate-FE-Deploy.git main